[package]
name = "metronome-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.12.1"
metronome-core = { version = "*", path = "../metronome-core" }
rusqlite = "0.31.0"
